import { createClient } from '@supabase/supabase-js';

// Load environment variables if available
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || 'http://127.0.0.1:54321';
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || 'service-role-key-placeholder';

const supabase = createClient(supabaseUrl, supabaseServiceKey);

export const SEED_SKILLS = [
  { name: 'Python', category: 'Programming', aliases: ['py', 'python3'] },
  { name: 'SQL', category: 'Data & Analytics', aliases: ['postgres', 'mysql', 'tsql'] },
  { name: 'JavaScript', category: 'Programming', aliases: ['js', 'ecmascript'] },
  { name: 'TypeScript', category: 'Programming', aliases: ['ts'] },
  { name: 'React', category: 'Frontend Development', aliases: ['reactjs', 'react.js'] },
  { name: 'Node.js', category: 'Backend Development', aliases: ['node', 'express'] },
  { name: 'HTML/CSS', category: 'Frontend Development', aliases: ['html5', 'css3'] },
  { name: 'Tailwind CSS', category: 'Frontend Development', aliases: ['tailwind'] },
  { name: 'Data Structures & Algorithms', category: 'Computer Science', aliases: ['dsa', 'algorithms'] },
  { name: 'System Design', category: 'Architecture', aliases: ['distributed systems'] },
  { name: 'Git & Version Control', category: 'DevOps & Tools', aliases: ['git', 'github'] },
  { name: 'Linux Administration', category: 'Systems & Cloud', aliases: ['linux', 'bash', 'shell'] },
  { name: 'Docker & Containers', category: 'DevOps & Cloud', aliases: ['docker', 'containerization'] },
  { name: 'AWS Cloud Fundamentals', category: 'Cloud Computing', aliases: ['aws', 'amazon web services'] },
  { name: 'Kubernetes', category: 'DevOps & Cloud', aliases: ['k8s'] },
  { name: 'CI/CD Pipelines', category: 'DevOps & Cloud', aliases: ['github actions', 'jenkins'] },
  { name: 'Excel & Advanced Formulas', category: 'Data & Analytics', aliases: ['excel', 'spreadsheet'] },
  { name: 'PowerBI', category: 'Data & Analytics', aliases: ['power bi'] },
  { name: 'Tableau', category: 'Data & Analytics', aliases: ['tableau dashboard'] },
  { name: 'Pandas & NumPy', category: 'Data & Analytics', aliases: ['pandas', 'numpy'] },
  { name: 'Statistics & Probability', category: 'Data & Analytics', aliases: ['stats'] },
  { name: 'Machine Learning Basics', category: 'Artificial Intelligence', aliases: ['ml', 'scikit-learn'] },
  { name: 'Deep Learning & PyTorch', category: 'Artificial Intelligence', aliases: ['pytorch', 'tensorflow'] },
  { name: 'Cybersecurity Fundamentals', category: 'Security', aliases: ['info-sec', 'cyber security'] },
  { name: 'Network Security', category: 'Security', aliases: ['firewall', 'tcp/ip'] },
  { name: 'Penetration Testing', category: 'Security', aliases: ['ethical hacking', 'pen test'] },
  { name: 'Security Audit & Compliance', category: 'Security', aliases: ['iso27001', 'nist'] },
  { name: 'Figma & UI Design', category: 'Design', aliases: ['figma', 'ui design'] },
  { name: 'User Research & Wireframing', category: 'Design', aliases: ['ux research', 'wireframes'] },
  { name: 'Product Management', category: 'Management', aliases: ['product roadmap', 'scrum'] },
  { name: 'Agile & Scrum Methodologies', category: 'Management', aliases: ['agile', 'jira'] },
  { name: 'Digital Marketing & SEO', category: 'Marketing', aliases: ['seo', 'sem', 'google analytics'] },
  { name: 'Content Strategy', category: 'Marketing', aliases: ['copywriting', 'content marketing'] },
  { name: 'Embedded C/C++', category: 'Hardware & Electronics', aliases: ['embedded c', 'microcontrollers'] },
  { name: 'PCB Design & VLSI', category: 'Hardware & Electronics', aliases: ['pcb', 'vlsi'] },
  { name: 'Internet of Things (IoT)', category: 'Hardware & Electronics', aliases: ['iot', 'arduino', 'raspberry pi'] },
  { name: 'Java Programming', category: 'Programming', aliases: ['java', 'jdk'] },
  { name: 'C++ Programming', category: 'Programming', aliases: ['cpp', 'cplusplus'] },
  { name: 'PostgreSQL Database', category: 'Backend Development', aliases: ['postgres'] },
  { name: 'REST API Development', category: 'Backend Development', aliases: ['restful', 'web api'] },
  { name: 'GraphQL', category: 'Backend Development', aliases: ['graphql api'] },
  { name: 'Microservices Architecture', category: 'Architecture', aliases: ['microservices'] },
  { name: 'Communication Skills', category: 'Soft Skills', aliases: ['verbal', 'presentation'] },
  { name: 'Problem Solving & Logic', category: 'Soft Skills', aliases: ['aptitude', 'critical thinking'] },
  { name: 'Business Analysis', category: 'Management', aliases: ['req gathering', 'gap analysis'] },
  { name: 'Financial Modeling', category: 'Finance', aliases: ['finance', 'cashflow'] },
  { name: 'Public Administration & E-Gov', category: 'Governance', aliases: ['e-governance', 'mp govt schemes'] },
  { name: 'Technical Writing', category: 'Documentation', aliases: ['documentation', 'api docs'] },
  { name: 'Risk Management', category: 'Management', aliases: ['risk analysis'] },
  { name: 'Database Administration', category: 'Database', aliases: ['dba', 'sql server'] },
];

export const SEED_CAREER_ROLES = [
  { title: 'Software Developer', category: 'Software Engineering', description: 'Designs, builds, tests and maintains software applications to solve real-world problems.', salary_range: '₹4.5 - ₹12 LPA', growth_outlook: 'High Demand (18% YoY Growth)' },
  { title: 'Data Analyst', category: 'Data & Analytics', description: 'Translates raw data into actionable insights for business decision-making and government policy planning.', salary_range: '₹4.0 - ₹10 LPA', growth_outlook: 'High Demand (22% YoY Growth)' },
  { title: 'Data Scientist', category: 'Data & Analytics', description: 'Builds predictive models, machine learning pipelines and advanced statistical algorithms.', salary_range: '₹6.0 - ₹16 LPA', growth_outlook: 'Very High Demand' },
  { title: 'Cybersecurity Analyst', category: 'Security', description: 'Monitors, detects and responds to digital security threats across enterprise and state infrastructure.', salary_range: '₹5.0 - ₹14 LPA', growth_outlook: 'Critical Govt & Private Demand' },
  { title: 'Cloud Engineer', category: 'Systems & Cloud', description: 'Architects and manages secure, scalable cloud infrastructure on AWS, Azure, or GCP.', salary_range: '₹5.5 - ₹15 LPA', growth_outlook: 'High Demand' },
  { title: 'UI/UX Designer', category: 'Design', description: 'Crafts intuitive, accessible human-centered user experiences and interface designs.', salary_range: '₹3.8 - ₹9.5 LPA', growth_outlook: 'Steady Growth' },
  { title: 'Product Manager', category: 'Management', description: 'Defines product vision, prioritizes roadmap features and coordinates engineering and design teams.', salary_range: '₹7.0 - ₹18 LPA', growth_outlook: 'High Demand' },
  { title: 'Electronics Engineer', category: 'Hardware', description: 'Designs embedded electronic circuits, IoT devices, microcontrollers and automation hardware.', salary_range: '₹3.5 - ₹8.5 LPA', growth_outlook: 'MP Industrial Hub Demand' },
  { title: 'Business Analyst', category: 'Management', description: 'Bridges business requirements with technological solutions through structured data and workflow analysis.', salary_range: '₹4.2 - ₹11 LPA', growth_outlook: 'Steady Demand' },
  { title: 'Digital Marketing Specialist', category: 'Marketing', description: 'Drives online brand visibility, audience engagement and digital growth campaigns.', salary_range: '₹3.0 - ₹7.5 LPA', growth_outlook: 'High Regional Demand' },
  { title: 'DevOps Engineer', category: 'Systems & Cloud', description: 'Automates deployment pipelines, infrastructure provisioning and system reliability.', salary_range: '₹6.0 - ₹16 LPA', growth_outlook: 'High Demand' },
  { title: 'Full Stack Developer', category: 'Software Engineering', description: 'Builds both front-end user interfaces and back-end database API services.', salary_range: '₹5.0 - ₹14 LPA', growth_outlook: 'High Demand' },
  { title: 'Systems Engineer', category: 'IT Infrastructure', description: 'Maintains IT server hardware, network backbones and operating system reliability.', salary_range: '₹3.6 - ₹8.0 LPA', growth_outlook: 'Steady Demand' },
  { title: 'Embedded Systems Engineer', category: 'Hardware', description: 'Develops low-level firmware code for smart sensors, automotive units and industrial machinery.', salary_range: '₹4.5 - ₹11 LPA', growth_outlook: 'High Hardware Demand' },
  { title: 'AI/ML Specialist', category: 'Artificial Intelligence', description: 'Researches and deploys generative AI models, natural language processing and computer vision applications.', salary_range: '₹8.0 - ₹22 LPA', growth_outlook: 'Exponential Growth' },
  { title: 'Network Engineer', category: 'IT Infrastructure', description: 'Configures switches, routers, VPNs and telecommunication infrastructure.', salary_range: '₹3.8 - ₹9.0 LPA', growth_outlook: 'Steady Demand' },
  { title: 'QA Automation Engineer', category: 'Software Engineering', description: 'Writes automated test suites to ensure software stability, security and performance.', salary_range: '₹4.0 - ₹10 LPA', growth_outlook: 'Steady Demand' },
  { title: 'Database Administrator', category: 'Data & Analytics', description: 'Ensures database availability, backup recovery, security access controls and query optimization.', salary_range: '₹4.8 - ₹12 LPA', growth_outlook: 'Steady Demand' },
];

export const SEED_COURSES = [
  { title: 'Data Structures and Algorithms', provider: 'NPTEL (IIT Kharagpur)', level: 'Intermediate', duration_hours: 48, url: 'https://nptel.ac.in/courses/106105085', is_free: true, price: 'Free' },
  { title: 'Full Stack Web Development', provider: 'SWAYAM (MHRD)', level: 'Intermediate', duration_hours: 60, url: 'https://swayam.gov.in/explorer', is_free: true, price: 'Free' },
  { title: 'Cloud Computing Fundamentals', provider: 'AWS Skill Builder', level: 'Beginner', duration_hours: 15, url: 'https://explore.skillbuilder.aws', is_free: true, price: 'Free' },
  { title: 'Google Data Analytics Professional Certificate', provider: 'Coursera', level: 'Beginner', duration_hours: 120, url: 'https://coursera.org/professional-certificates/google-data-analytics', is_free: false, price: 'Financial Aid Available' },
  { title: 'Meta Front-End Developer Certificate', provider: 'Coursera', level: 'Beginner', duration_hours: 90, url: 'https://coursera.org/professional-certificates/meta-front-end-developer', is_free: false, price: 'Financial Aid Available' },
  { title: 'Cisco CCNA Networking Basics', provider: 'Cisco Networking Academy', level: 'Beginner', duration_hours: 70, url: 'https://netacad.com', is_free: true, price: 'Free' },
  { title: 'CompTIA Security+ Exam Prep', provider: 'edX', level: 'Intermediate', duration_hours: 40, url: 'https://edx.org', is_free: true, price: 'Free Audit' },
  { title: 'Machine Learning by Andrew Ng', provider: 'Coursera / DeepLearning.AI', level: 'Intermediate', duration_hours: 80, url: 'https://coursera.org/specializations/machine-learning-introduction', is_free: false, price: 'Financial Aid Available' },
  { title: 'PostgreSQL Bootcamp & Administration', provider: 'SWAYAM', level: 'Intermediate', duration_hours: 30, url: 'https://swayam.gov.in', is_free: true, price: 'Free' },
  { title: 'UI/UX Design Essentials in Figma', provider: 'Udemy', level: 'Beginner', duration_hours: 20, url: 'https://udemy.com', is_free: false, price: '₹499' },
  { title: 'Python for Data Science', provider: 'NPTEL (IIT Madras)', level: 'Beginner', duration_hours: 36, url: 'https://nptel.ac.in', is_free: true, price: 'Free' },
  { title: 'Cybersecurity Fundamentals & Ethical Hacking', provider: 'NPTEL', level: 'Beginner', duration_hours: 45, url: 'https://nptel.ac.in', is_free: true, price: 'Free' },
  { title: 'DevOps & Kubernetes Masterclass', provider: 'edX', level: 'Advanced', duration_hours: 50, url: 'https://edx.org', is_free: true, price: 'Free Audit' },
  { title: 'Embedded Systems & Microcontrollers', provider: 'NPTEL (IIT Bombay)', level: 'Intermediate', duration_hours: 40, url: 'https://nptel.ac.in', is_free: true, price: 'Free' },
  { title: 'Product Management Fundamentals', provider: 'SWAYAM', level: 'Beginner', duration_hours: 25, url: 'https://swayam.gov.in', is_free: true, price: 'Free' },
  { title: 'Digital Marketing & Social Media Strategy', provider: 'Google Digital Unlocked', level: 'Beginner', duration_hours: 40, url: 'https://skillshop.exceedlms.com', is_free: true, price: 'Free Certificate' },
  { title: 'Java Programming & OOP Concepts', provider: 'NPTEL', level: 'Beginner', duration_hours: 48, url: 'https://nptel.ac.in', is_free: true, price: 'Free' },
  { title: 'System Design & High Scalability Architecture', provider: 'edX', level: 'Advanced', duration_hours: 35, url: 'https://edx.org', is_free: true, price: 'Free Audit' },
  { title: 'Business Analytics with Excel & PowerBI', provider: 'Microsoft Learn', level: 'Beginner', duration_hours: 24, url: 'https://learn.microsoft.com', is_free: true, price: 'Free' },
  { title: 'Agile & Scrum Project Management', provider: 'Coursera', level: 'Beginner', duration_hours: 20, url: 'https://coursera.org', is_free: false, price: 'Financial Aid Available' },
  { title: 'Linux System Administration & Shell Scripting', provider: 'edX (Linux Foundation)', level: 'Intermediate', duration_hours: 60, url: 'https://edx.org', is_free: true, price: 'Free Audit' },
  { title: 'Deep Learning & Neural Networks', provider: 'DeepLearning.AI', level: 'Advanced', duration_hours: 75, url: 'https://deeplearning.ai', is_free: false, price: 'Paid' },
  { title: 'Rest API Design with Node & Express', provider: 'FreeCodeCamp', level: 'Intermediate', duration_hours: 15, url: 'https://freecodecamp.org', is_free: true, price: 'Free' },
  { title: 'Public Policy & E-Governance in India', provider: 'SWAYAM (IIM Bangalore)', level: 'Intermediate', duration_hours: 32, url: 'https://swayam.gov.in', is_free: true, price: 'Free' },
  { title: 'Effective Business Communication & Soft Skills', provider: 'NPTEL', level: 'Beginner', duration_hours: 20, url: 'https://nptel.ac.in', is_free: true, price: 'Free' },
];

export const SEED_OPPORTUNITIES = [
  {
    title: 'Software Engineering Intern',
    organization: 'National Informatics Centre (NIC MP State Unit)',
    type: 'internship',
    location: 'Bhopal, MP / Hybrid',
    eligibility: 'B.Tech / BE (CSE, IT, ECE) 6th-8th Sem or MCA students with minimum 60% CGPA.',
    application_deadline: '2026-10-31',
    employment_type: 'internship',
    organization_type: 'government',
    education_requirements: 'B.Tech / MCA',
    experience_required: 'Fresher / Student',
    status: 'active',
    url: 'https://nic.in/careers',
    source: 'NIC India Official Portal',
    source_url: 'https://nic.in',
    is_verified: true,
    verified_at: '2026-09-01T00:00:00Z',
  },
  {
    title: 'Graduate Engineer Trainee (GET - IT)',
    organization: 'Bharat Heavy Electricals Limited (BHEL Bhopal)',
    type: 'job',
    location: 'Bhopal, MP',
    eligibility: 'BE / B.Tech in CSE / Electrical / Mechanical with GATE score or 65%+ aggregate.',
    application_deadline: '2026-11-15',
    employment_type: 'full_time',
    organization_type: 'psu',
    education_requirements: 'B.Tech / BE',
    experience_required: '0-1 Year',
    status: 'active',
    url: 'https://careers.bhel.in',
    source: 'BHEL Careers Portal',
    source_url: 'https://bhel.in',
    is_verified: true,
    verified_at: '2026-09-02T00:00:00Z',
  },
  {
    title: 'MP State IT & E-Governance Fellowship',
    organization: 'MP State Electronics Development Corporation (MPSEDC)',
    type: 'apprentice',
    location: 'Bhopal / Indore, MP',
    eligibility: 'Graduates in Engineering, Computer Applications, or Data Science from MP universities.',
    application_deadline: '2026-10-15',
    employment_type: 'contract',
    organization_type: 'state_govt',
    education_requirements: 'Graduation in IT/CS',
    experience_required: 'Fresher',
    status: 'active',
    url: 'https://mpsedc.mp.gov.in',
    source: 'MPSEDC Official Portal',
    source_url: 'https://mpsedc.mp.gov.in',
    is_verified: true,
    verified_at: '2026-08-28T00:00:00Z',
  },
  {
    title: 'Junior Data Analyst',
    organization: 'MP Industrial Development Corporation (MPIDC)',
    type: 'job',
    location: 'Indore, MP',
    eligibility: 'Bachelor degree in Computer Science, Statistics, Economics or Mathematics. SQL proficiency required.',
    application_deadline: '2026-11-30',
    employment_type: 'full_time',
    organization_type: 'state_govt',
    education_requirements: 'B.Sc / B.Tech / BCA',
    experience_required: '0-2 Years',
    status: 'active',
    url: 'https://mpidc.co.in',
    source: 'MPIDC Employment Portal',
    source_url: 'https://mpidc.co.in',
    is_verified: true,
    verified_at: '2026-09-04T00:00:00Z',
  },
  {
    title: 'Cybersecurity Associate Specialist',
    organization: 'MP Police IT & Cyber Crime Cell',
    type: 'job',
    location: 'Bhopal, MP',
    eligibility: 'B.Tech / MCA with cybersecurity certification or coursework in network security and forensics.',
    application_deadline: '2026-12-01',
    employment_type: 'contract',
    organization_type: 'state_govt',
    education_requirements: 'B.Tech / MCA',
    experience_required: '0-1 Year',
    status: 'active',
    url: 'https://mppolice.gov.in',
    source: 'MP Police Recruitment Cell',
    source_url: 'https://mppolice.gov.in',
    is_verified: true,
    verified_at: '2026-09-05T00:00:00Z',
  },
  {
    title: 'Associate Cloud Engineer (Demo Role)',
    organization: 'Indore Tech Park Innovations',
    type: 'job',
    location: 'Indore, MP',
    eligibility: 'B.Tech CS/IT with knowledge of AWS or Azure fundamentals and Linux administration.',
    application_deadline: '2026-10-25',
    employment_type: 'full_time',
    organization_type: 'private',
    education_requirements: 'B.Tech / BCA',
    experience_required: '0-1 Year',
    status: 'active',
    url: 'https://example-demo.mpcareersetu.in/cloud-job',
    source: 'Hackathon Demo Dataset',
    source_url: 'https://mpcareersetu.in',
    is_verified: false,
    verified_at: null,
  },
  {
    title: 'UI/UX Design Apprentice (Demo Role)',
    organization: 'Central India Digital Agency',
    type: 'apprentice',
    location: 'Gwalior, MP / Remote',
    eligibility: 'Portfolio of 2-3 UI/UX wireframes or Figma mockups. Good grasp of user research principles.',
    application_deadline: '2026-11-10',
    employment_type: 'internship',
    organization_type: 'private',
    education_requirements: 'Any Graduate / Student',
    experience_required: 'Fresher',
    status: 'active',
    url: 'https://example-demo.mpcareersetu.in/ux-intern',
    source: 'Hackathon Demo Dataset',
    source_url: 'https://mpcareersetu.in',
    is_verified: false,
    verified_at: null,
  },
  {
    title: 'Junior Embedded Firmware Trainee (Demo Role)',
    organization: 'Pithampur Electronics Hub Ltd',
    type: 'job',
    location: 'Pithampur, Dhar, MP',
    eligibility: 'B.E / B.Tech in Electronics, Electrical or Instrumentation. Knowledge of Embedded C and microcontrollers.',
    application_deadline: '2026-10-20',
    employment_type: 'full_time',
    organization_type: 'private',
    education_requirements: 'BE / B.Tech (ECE/EEE)',
    experience_required: '0-1 Year',
    status: 'active',
    url: 'https://example-demo.mpcareersetu.in/embedded-trainee',
    source: 'Hackathon Demo Dataset',
    source_url: 'https://mpcareersetu.in',
    is_verified: false,
    verified_at: null,
  },
  {
    title: 'Assistant Programmer (MP State Service Exam)',
    organization: 'MP Public Service Commission (MPPSC)',
    type: 'govt_exam',
    location: 'Across MP',
    eligibility: 'Degree in Computer Science/Applications. MP PSC examination qualification mandatory.',
    application_deadline: '2026-12-15',
    employment_type: 'full_time',
    organization_type: 'state_govt',
    education_requirements: 'B.Tech CS / MCA / B.Sc CS',
    experience_required: 'Fresher (Exam Based)',
    status: 'active',
    url: 'https://mppsc.mp.gov.in',
    source: 'MPPSC Official Website',
    source_url: 'https://mppsc.mp.gov.in',
    is_verified: true,
    verified_at: '2026-08-30T00:00:00Z',
  },
  {
    title: 'Digital Marketing & Content Specialist (Demo Role)',
    organization: 'Jabalpur Smart City Corporation',
    type: 'job',
    location: 'Jabalpur, MP',
    eligibility: 'Degree in Communications, Marketing, or CS with experience in social media analytics and SEO.',
    application_deadline: '2026-10-30',
    employment_type: 'contract',
    organization_type: 'govt_undertaking',
    education_requirements: 'Any Graduate',
    experience_required: '0-2 Years',
    status: 'active',
    url: 'https://example-demo.mpcareersetu.in/marketing-role',
    source: 'Hackathon Demo Dataset',
    source_url: 'https://mpcareersetu.in',
    is_verified: false,
    verified_at: null,
  },
  {
    title: 'Python Backend Developer Intern (Demo Role)',
    organization: 'Bhopal FinTech Solutions',
    type: 'internship',
    location: 'Bhopal, MP',
    eligibility: 'Good command of Python, SQL, REST APIs, and version control (Git).',
    application_deadline: '2026-11-05',
    employment_type: 'internship',
    organization_type: 'private',
    education_requirements: 'B.Tech / BCA / MCA Student',
    experience_required: 'Student',
    status: 'active',
    url: 'https://example-demo.mpcareersetu.in/python-intern',
    source: 'Hackathon Demo Dataset',
    source_url: 'https://mpcareersetu.in',
    is_verified: false,
    verified_at: null,
  },
  {
    title: 'Business Analyst Associate (Demo Role)',
    organization: 'Indore IT SEZ Consulting Services',
    type: 'job',
    location: 'Indore, MP',
    eligibility: 'BBA / B.Tech / MBA with strong analytical skills, Excel modeling, and requirement documentation capability.',
    application_deadline: '2026-11-20',
    employment_type: 'full_time',
    organization_type: 'private',
    education_requirements: 'B.Tech / BBA / MBA',
    experience_required: '0-1 Year',
    status: 'active',
    url: 'https://example-demo.mpcareersetu.in/ba-associate',
    source: 'Hackathon Demo Dataset',
    source_url: 'https://mpcareersetu.in',
    is_verified: false,
    verified_at: null,
  },
  {
    title: 'QA Automation Engineer Trainee (Demo Role)',
    organization: 'Central Software Tech Bhopal',
    type: 'job',
    location: 'Bhopal, MP',
    eligibility: 'B.Tech in CS/IT with basic understanding of Java or Python automation frameworks.',
    application_deadline: '2026-11-12',
    employment_type: 'full_time',
    organization_type: 'private',
    education_requirements: 'B.Tech / MCA',
    experience_required: '0-1 Year',
    status: 'active',
    url: 'https://example-demo.mpcareersetu.in/qa-role',
    source: 'Hackathon Demo Dataset',
    source_url: 'https://mpcareersetu.in',
    is_verified: false,
    verified_at: null,
  },
  {
    title: 'AI/ML Engineering Apprentice (Demo Role)',
    organization: 'MP AI Innovation Lab',
    type: 'apprentice',
    location: 'Indore, MP / Hybrid',
    eligibility: 'Python, NumPy/Pandas, and familiarity with PyTorch or Scikit-Learn.',
    application_deadline: '2026-11-28',
    employment_type: 'internship',
    organization_type: 'private',
    education_requirements: 'B.Tech / M.Tech in CS/AI',
    experience_required: 'Fresher',
    status: 'active',
    url: 'https://example-demo.mpcareersetu.in/aiml-apprentice',
    source: 'Hackathon Demo Dataset',
    source_url: 'https://mpcareersetu.in',
    is_verified: false,
    verified_at: null,
  },
  {
    title: 'Network Systems Technician (Demo Role)',
    organization: 'Ujjain Smart Infrastructure Ltd',
    type: 'job',
    location: 'Ujjain, MP',
    eligibility: 'Diploma or BE in Electronics/CS with Cisco CCNA or networking fundamentals.',
    application_deadline: '2026-10-28',
    employment_type: 'full_time',
    organization_type: 'private',
    education_requirements: 'Diploma / BE',
    experience_required: '0-2 Years',
    status: 'active',
    url: 'https://example-demo.mpcareersetu.in/network-tech',
    source: 'Hackathon Demo Dataset',
    source_url: 'https://mpcareersetu.in',
    is_verified: false,
    verified_at: null,
  },
];

async function main() {
  console.log('🌱 Starting Seed Script for MP CareerSetu...');

  // 1. Seed Skills
  console.log('Seeding skills...');
  const { data: skillsData, error: skillsError } = await supabase
    .from('skills')
    .upsert(SEED_SKILLS, { onConflict: 'name' })
    .select();
  if (skillsError) console.error('Error seeding skills:', skillsError);
  else console.log(`✓ Seeded ${skillsData.length} skills`);

  // 2. Seed Career Roles
  console.log('Seeding career roles...');
  const { data: rolesData, error: rolesError } = await supabase
    .from('career_roles')
    .upsert(SEED_CAREER_ROLES, { onConflict: 'title' })
    .select();
  if (rolesError) console.error('Error seeding career roles:', rolesError);
  else console.log(`✓ Seeded ${rolesData.length} career roles`);

  // 3. Seed Courses
  console.log('Seeding courses...');
  const { data: coursesData, error: coursesError } = await supabase
    .from('courses')
    .upsert(SEED_COURSES, { onConflict: 'title' })
    .select();
  if (coursesError) console.error('Error seeding courses:', coursesError);
  else console.log(`✓ Seeded ${coursesData.length} courses`);

  // 4. Seed Opportunities
  console.log('Seeding opportunities...');
  const { data: oppsData, error: oppsError } = await supabase
    .from('opportunities')
    .upsert(SEED_OPPORTUNITIES, { onConflict: 'title' })
    .select();
  if (oppsError) console.error('Error seeding opportunities:', oppsError);
  else console.log(`✓ Seeded ${oppsData.length} opportunities`);

  console.log('🎉 Seeding complete!');
}

main().catch(console.error);
