'use client';

import React, { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, BriefcaseBusiness, CalendarDays, Filter, MapPin, Search, ShieldCheck, Target } from 'lucide-react';
import { Sidebar } from '@/components/layout/sidebar';
import { TopNav } from '@/components/layout/top-nav';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select } from '@/components/ui/select';
import { EmptyState } from '@/components/ui/empty-state';
import { LoadingState } from '@/components/ui/loading-state';
import { getOpportunityMatches } from '@/lib/matching/actions';

type Match = { opportunity: { id: string; title: string; organization: string; location: string; application_deadline?: string; source: string; source_url?: string; is_verified: boolean; type?: string; status?: string }; score: number; reasons: string[]; eligibility?: 'satisfied' | 'unknown' | 'not_established' };

export default function OpportunitiesPage() {
  const [matches, setMatches] = useState<Match[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [search, setSearch] = useState(''); const [tab, setTab] = useState('All Opportunities'); const [type, setType] = useState('all'); const [location, setLocation] = useState('all'); const [selected, setSelected] = useState<Match | null>(null);
  useEffect(() => { void getOpportunityMatches().then((result) => { if (result.success) { const next = (result.matches || []) as Match[]; setMatches(next); setSelected(next[0] || null); } else setError(result.error || 'Opportunities are unavailable.'); setLoading(false); }).catch(() => { setError('Opportunities are unavailable.'); setLoading(false); }); }, []);
  const types = useMemo(() => Array.from(new Set(matches.map((match) => match.opportunity.type).filter(Boolean))) as string[], [matches]); const locations = useMemo(() => Array.from(new Set(matches.map((match) => match.opportunity.location).filter(Boolean))) as string[], [matches]);
  const filtered = useMemo(() => matches.filter((match) => { const opportunity = match.opportunity; const haystack = `${opportunity.title} ${opportunity.organization} ${opportunity.location}`.toLowerCase(); const tabMatch = tab === 'All Opportunities' || opportunity.type?.toLowerCase() === tab.toLowerCase().replace(/s$/, ''); const typeMatch = type === 'all' || opportunity.type === type; const locationMatch = location === 'all' || opportunity.location === location; return tabMatch && typeMatch && locationMatch && haystack.includes(search.toLowerCase()); }), [matches, search, tab, type, location]);
  useEffect(() => { if (selected && !filtered.some((match) => match.opportunity.id === selected.opportunity.id)) setSelected(filtered[0] || null); }, [filtered, selected]);
  const average = matches.length ? Math.round(matches.reduce((sum, match) => sum + match.score, 0) / matches.length) : null; const deadlines = [...matches].filter((match) => match.opportunity.application_deadline).sort((a, b) => String(a.opportunity.application_deadline).localeCompare(String(b.opportunity.application_deadline))).slice(0, 4);

  return <div className="min-h-screen bg-[#f4f8fc] flex"><Sidebar /><div className="flex min-w-0 flex-1 flex-col"><TopNav /><main className="mx-auto w-full max-w-[1440px] flex-1 space-y-4 p-4 sm:p-6">
    <section className="relative min-h-[175px] overflow-hidden border border-blue-100 bg-[#e8f2ff] px-5 py-7 sm:px-8"><div className="absolute inset-y-0 right-0 w-1/2 bg-[url('/opportunities-hero.jpg')] bg-cover bg-right opacity-40" /><div className="absolute inset-0 bg-gradient-to-r from-[#e8f2ff] via-[#e8f2ff]/90 to-transparent" /><div className="relative max-w-[620px]"><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#1559c7]">Opportunities</p><h1 className="mt-2 text-3xl font-extrabold text-[#10295d] sm:text-4xl">Explore Opportunities</h1><p className="mt-2 text-sm leading-5 text-[#536987]">Browse internships, jobs, fellowships, hackathons, and programs matched to your skills and career interests.</p></div></section>
    <section className="flex gap-1 overflow-x-auto border-b border-[#dce7f2] bg-white px-3 py-3 text-sm font-semibold">{['All Opportunities', 'Internships', 'Jobs', 'Fellowships', 'Hackathons', 'Competitions', 'Government Programs'].map((item) => <button key={item} type="button" onClick={() => setTab(item)} className={`whitespace-nowrap border-b-2 px-3 py-2 ${tab === item ? 'border-[#1559c7] text-[#1559c7]' : 'border-transparent text-slate-500'}`}>{item}</button>)}</section>
    <section className="flex flex-col gap-2 border border-[#dce7f2] bg-white p-3 lg:flex-row"><div className="relative min-w-0 flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search opportunities..." className="h-9 pl-9 text-xs" /></div><Select value={type} onChange={(event) => setType(event.target.value)} className="h-9 text-xs lg:w-40"><option value="all">All types</option>{types.map((item) => <option key={item} value={item}>{item}</option>)}</Select><Select value={location} onChange={(event) => setLocation(event.target.value)} className="h-9 text-xs lg:w-44"><option value="all">All locations</option>{locations.map((item) => <option key={item} value={item}>{item}</option>)}</Select><Button variant="outline" size="sm" className="text-xs" onClick={() => { setSearch(''); setType('all'); setLocation('all'); setTab('All Opportunities'); }}><Filter className="h-3.5 w-3.5" />Reset</Button></section>
    {loading ? <div className="flex min-h-[300px] items-center justify-center"><LoadingState label="Finding matching opportunities..." /></div> : error ? <div className="border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div> : !matches.length ? <div className="bg-white p-10"><EmptyState icon={<BriefcaseBusiness className="h-10 w-10 text-slate-400" />} title="No matching opportunities" description="No active catalog opportunities currently match your available profile evidence." /></div> : <section className="grid grid-cols-1 gap-4 xl:grid-cols-[1fr_330px]"><div><div className="mb-3 flex items-center justify-between"><div><h2 className="text-lg sm:text-xl font-extrabold text-[#10295d]">Matched opportunities</h2><p className="mt-1 text-xs text-slate-500">Ranked by the deterministic opportunity matcher.</p></div><span className="text-xs text-[#1559c7]">{filtered.length} shown</span></div>{filtered.length ? <div className="space-y-2">{filtered.map((match) => <OpportunityRow key={match.opportunity.id} match={match} selected={selected?.opportunity.id === match.opportunity.id} onSelect={() => setSelected(match)} />)}</div> : <div className="bg-white p-8"><EmptyState title="No opportunities match these filters" description="Try another category, location, or search term." actionLabel="Reset filters" onAction={() => { setSearch(''); setType('all'); setLocation('all'); setTab('All Opportunities'); }} /></div>}</div><aside className="space-y-4"><MatchPanel score={average} count={matches.length} /><DeadlinePanel deadlines={deadlines} /><section className="border border-[#dce7f2] bg-white p-5"><h2 className="text-base font-bold text-[#10295d]">Eligibility and verification</h2><p className="mt-2 text-xs leading-5 text-slate-500">Eligibility remains unknown unless the stored profile data proves the catalog requirement. Verification reflects only the opportunity record&apos;s metadata.</p></section></aside></section>}
  </main></div></div>;
}

function OpportunityRow({ match, selected, onSelect }: { match: Match; selected: boolean; onSelect: () => void }) { const opportunity = match.opportunity; return <article onClick={onSelect} className={`flex cursor-pointer flex-col gap-3 border bg-white p-4 transition-colors sm:flex-row sm:items-center ${selected ? 'border-[#9dbce7] bg-[#f5f9ff]' : 'border-[#dce7f2] hover:border-[#9dbce7]'}`}><div className="flex h-12 w-12 shrink-0 items-center justify-center bg-[#edf4ff] text-[#1559c7]"><BriefcaseBusiness className="h-6 w-6" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg sm:text-xl font-bold text-[#10295d]">{opportunity.title}</h3><Badge variant={opportunity.is_verified ? 'verified' : 'secondary'} className="text-xs">{opportunity.is_verified ? 'Verified' : 'Unverified'}</Badge></div><p className="mt-1 text-xs font-semibold text-slate-700">{opportunity.organization}</p><div className="mt-2 flex flex-wrap gap-2 text-xs text-slate-500"><span className="rounded bg-[#f5f8fc] px-2 py-1">{opportunity.type || 'Type unavailable'}</span><span className="flex items-center gap-1"><MapPin className="h-3.5 w-3.5" />{opportunity.location || 'Location unknown'}</span><span className="flex items-center gap-1"><CalendarDays className="h-3.5 w-3.5" />{opportunity.application_deadline ? `Apply by ${opportunity.application_deadline}` : 'Deadline unknown'}</span></div><p className="mt-2 text-xs text-slate-500">{match.reasons[0]}</p></div><div className="flex shrink-0 flex-row items-center gap-2 sm:flex-col sm:items-end"><Badge variant={match.score >= 70 ? 'success' : 'info'} className="text-xs">{match.score}% match</Badge><span className="text-xs font-medium text-amber-700">Eligibility unknown</span><Link href={`/opportunities/${opportunity.id}`} onClick={(event) => event.stopPropagation()}><Button variant="outline" size="sm" className="text-xs">View details <ArrowRight className="h-3.5 w-3.5" /></Button></Link></div></article>; }
function MatchPanel({ score, count }: { score: number | null; count: number }) { return <section className="border border-[#dce7f2] bg-white p-5"><h2 className="flex items-center gap-2 text-base font-bold text-[#10295d]"><Target className="h-4.5 w-4.5 text-[#1559c7]" />Your opportunity match</h2><div className="mt-4 flex items-center gap-5"><div className="flex h-24 w-24 items-center justify-center rounded-full border-[7px] border-[#299b62] border-l-[#1559c7] border-b-[#dce7f2]"><strong className="text-2xl text-[#10295d]">{score === null ? '—' : `${score}%`}</strong></div><div className="text-xs leading-5 text-slate-500"><p>Average of {count} active matched catalog records.</p><p className="font-semibold text-[#1559c7]">Scores remain server-calculated.</p></div></div></section>; }
function DeadlinePanel({ deadlines }: { deadlines: Match[] }) { return <section className="border border-[#dce7f2] bg-white p-5"><h2 className="flex items-center gap-2 text-base font-bold text-[#10295d]"><CalendarDays className="h-4.5 w-4.5 text-[#1559c7]" />Upcoming deadlines</h2>{deadlines.length ? <div className="mt-3 divide-y divide-[#e5edf5]">{deadlines.map((match) => <Link href={`/opportunities/${match.opportunity.id}`} key={match.opportunity.id} className="flex gap-3 py-3"><span className="flex h-8 w-10 shrink-0 items-center justify-center bg-[#fff1f1] text-xs font-bold text-[#c84f5b]">{String(match.opportunity.application_deadline).slice(5, 10)}</span><span className="min-w-0"><strong className="block truncate text-sm text-[#10295d]">{match.opportunity.title}</strong><span className="text-xs text-slate-500">{match.opportunity.type || 'Opportunity'} · {match.opportunity.organization}</span></span></Link>)}</div> : <p className="mt-3 text-xs text-slate-500">No catalog deadlines are currently available.</p>}</section>; }
