'use client';

import React from 'react';

import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, BarChart3, BookOpen, Filter, Leaf, Palette, Search, Target, Users, X } from 'lucide-react';
import { Sidebar } from '@/components/layout/sidebar';
import { TopNav } from '@/components/layout/top-nav';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { LoadingState } from '@/components/ui/loading-state';
import { EmptyState } from '@/components/ui/empty-state';
import { getCourseRecommendations } from '@/lib/courses/actions';

type Match = { course: { id: string; title: string; provider: string; level: string; duration_hours?: number; url: string; is_free: boolean; price?: string; skills?: Array<{ id: string; name: string; category: string }> }; score: number; reasons: string[]; missingSkillIds: string[]; developingSkillIds: string[]; roleAlignedSkillIds: string[] };

export default function CoursesPage() {
  const [matches, setMatches] = useState<Match[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [search, setSearch] = useState(''); const [activeTab, setActiveTab] = useState('All Courses'); const [activeCategory, setActiveCategory] = useState('All');
  useEffect(() => { void getCourseRecommendations().then((result) => { if (result.success) setMatches((result.courses || []) as Match[]); else setError(result.error || 'Course catalog is unavailable.'); setLoading(false); }).catch(() => { setError('Course catalog is unavailable.'); setLoading(false); }); }, []);
  const categories = useMemo(() => { const values = new Set((matches.flatMap((match) => match.course.skills || [])).map((skill) => skill.category).filter(Boolean)); return ['All', ...Array.from(values).slice(0, 6)]; }, [matches]);
  const filtered = useMemo(() => matches.filter((match) => { const haystack = `${match.course.title} ${match.course.provider} ${(match.course.skills || []).map((skill) => skill.name).join(' ')}`.toLowerCase(); const categoryMatch = activeCategory === 'All' || (match.course.skills || []).some((skill) => skill.category === activeCategory); const tabMatch = activeTab === 'All Courses' || (activeTab === 'Free Courses' && match.course.is_free) || (activeTab === 'Certifications' && Boolean(match.course.url)); return categoryMatch && tabMatch && haystack.includes(search.toLowerCase()); }), [matches, search, activeCategory, activeTab]);
  const skillFit = matches.length ? Math.round(matches.reduce((sum, match) => sum + match.score, 0) / matches.length) : null; const strong = matches.filter((match) => match.score >= 70).length; const moderate = matches.filter((match) => match.score >= 40 && match.score < 70).length;

  return <div className="min-h-screen bg-[#f4f8fc] flex"><Sidebar /><div className="flex min-w-0 flex-1 flex-col"><TopNav /><main className="mx-auto w-full max-w-[1440px] flex-1 space-y-4 p-4 sm:p-6">
    <section className="relative min-h-[175px] overflow-hidden border border-blue-100 bg-[#e8f2ff] px-5 py-7 sm:px-8"><div className="absolute inset-y-0 right-0 w-1/2 bg-[url('/courses-hero.jpg')] bg-cover bg-right opacity-40" /><div className="absolute inset-0 bg-gradient-to-r from-[#e8f2ff] via-[#e8f2ff]/90 to-transparent" /><div className="relative max-w-[620px]"><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-[#1559c7]">Courses &amp; Certifications</p><h1 className="mt-2 text-3xl font-extrabold text-[#10295d] sm:text-4xl">Learning Resources</h1><p className="mt-2 text-sm leading-5 text-[#536987]">Discover catalog learning resources mapped to your recorded skills, target role, and current gaps.</p></div></section>
    <section className="flex flex-col gap-3 border-b border-[#dce7f2] bg-white px-3 py-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex gap-1 overflow-x-auto text-xs font-semibold">{['All Courses', 'By Career', 'By Skill', 'By Platform', 'Free Courses', 'Certifications'].map((tab) => <button key={tab} type="button" onClick={() => setActiveTab(tab)} className={`whitespace-nowrap border-b-2 px-3 py-2 ${activeTab === tab ? 'border-[#1559c7] text-[#1559c7]' : 'border-transparent text-slate-500'}`}>{tab}</button>)}</div><div className="flex gap-2"><div className="relative min-w-0 flex-1 sm:w-64"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search for courses..." className="h-9 pl-9 text-xs" /></div><Button variant="outline" size="sm"><Filter className="h-3.5 w-3.5" />Filters</Button></div></section>
    <section className="flex gap-2 overflow-x-auto">{categories.map((category) => <button key={category} type="button" onClick={() => setActiveCategory(category)} className={`flex min-w-[112px] flex-col items-center justify-center gap-2 border px-4 py-3 text-center text-[10px] font-semibold ${activeCategory === category ? 'border-[#9dbce7] bg-[#edf4ff] text-[#1559c7]' : 'border-[#dce7f2] bg-white text-slate-600'}`}><CategoryIcon category={category} />{category}</button>)}</section>
    {loading ? <div className="flex min-h-[300px] items-center justify-center"><LoadingState label="Finding relevant catalog courses..." /></div> : error ? <div className="border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div> : !matches.length ? <div className="bg-white p-10"><EmptyState icon={<BookOpen className="h-10 w-10 text-slate-400" />} title="No courses available" description="No catalog courses are currently available for this profile." /></div> : <section className="grid grid-cols-1 gap-4 xl:grid-cols-[1fr_330px]"><div><div className="mb-3 flex items-center justify-between"><div><h2 className="text-base font-extrabold text-[#10295d]">Popular courses for you</h2><p className="mt-1 text-xs text-slate-500">Ranked by deterministic skill-gap and target-role relevance.</p></div><span className="text-xs text-[#1559c7]">{filtered.length} shown</span></div>{!filtered.length ? <div className="bg-white p-8"><EmptyState title="No matching catalog courses" description="Try another search, category, or tab." actionLabel="Clear filters" onAction={() => { setSearch(''); setActiveCategory('All'); setActiveTab('All Courses'); }} /></div> : <div className="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-3">{filtered.map((match) => <CourseCard key={match.course.id} match={match} />)}</div>}</div><aside className="space-y-4"><SkillFit score={skillFit} strong={strong} moderate={moderate} total={matches.length} /><LearningPath matches={matches} /><div className="border border-[#dce7f2] bg-white p-5"><h2 className="text-sm font-bold text-[#10295d]">My certifications</h2><p className="mt-2 text-xs leading-5 text-slate-500">Completion tracking is not available in the current catalog schema.</p><span className="mt-3 inline-flex items-center gap-1 text-[10px] text-slate-400"><X className="h-3 w-3" /> No persisted certificates</span></div></aside></section>}
    
  </main></div></div>;
}

function CategoryIcon({ category }: { category: string }) { const Icon = category === 'Data & AI' ? BarChart3 : category === 'Design' ? Palette : category === 'Environment' ? Leaf : category === 'Business' ? Users : BookOpen; return <Icon className="h-5 w-5 text-[#1559c7]" />; }
function CourseCard({ match }: { match: Match }) { const course = match.course; return <article className="flex min-h-[225px] flex-col justify-between border border-[#dce7f2] bg-white p-4 shadow-[0_2px_8px_rgba(25,70,120,0.035)]"><div><div className="flex items-start justify-between gap-2"><div className="flex h-8 w-12 items-center justify-center bg-[#f1f6fb] text-[10px] font-bold text-[#1559c7]">{course.provider.slice(0, 5).toUpperCase()}</div><Badge variant={course.is_free ? 'success' : 'warning'} className="text-[9px]">{course.is_free ? 'Free' : course.price || 'Paid'}</Badge></div><h3 className="mt-3 line-clamp-2 text-sm font-bold text-[#10295d]">{course.title}</h3><p className="mt-1 text-[10px] text-slate-500">{course.provider}</p><div className="mt-3 flex flex-wrap gap-1 text-[9px] text-slate-500">{course.level && <span className="rounded bg-[#f5f8fc] px-1.5 py-1">{course.level}</span>}{course.duration_hours ? <span className="rounded bg-[#f5f8fc] px-1.5 py-1">{course.duration_hours} hours</span> : <span className="rounded bg-[#f5f8fc] px-1.5 py-1">Duration unavailable</span>}<span className="rounded bg-[#f5f8fc] px-1.5 py-1">{course.skills?.length || 0} mapped skills</span></div></div><div><p className="mt-3 line-clamp-2 text-[10px] text-slate-500">{match.reasons[0]}</p><div className="mt-3 flex items-center justify-between"><Badge variant={match.score >= 70 ? 'success' : 'info'} className="text-[9px]">{match.score}% skill fit</Badge><a href={course.url} target="_blank" rel="noreferrer"><Button variant="outline" size="sm" className="text-[10px]">View course <ArrowRight className="h-3 w-3" /></Button></a></div></div></article>; }
function SkillFit({ score, strong, moderate, total }: { score: number | null; strong: number; moderate: number; total: number }) { return <section className="border border-[#dce7f2] bg-white p-5"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 text-sm font-bold text-[#10295d]"><Target className="h-4 w-4 text-[#1559c7]" />Your skill fit</h2><span className="text-[10px] text-[#1559c7]">Catalog view</span></div><div className="mt-4 flex items-center gap-5"><div className="flex h-24 w-24 items-center justify-center rounded-full border-[7px] border-[#299b62] border-l-[#1559c7] border-b-[#dce7f2]"><strong className="text-2xl text-[#10295d]">{score === null ? '—' : `${score}%`}</strong></div><div className="space-y-2 text-[10px] text-slate-600"><p><span className="mr-2 inline-block h-2 w-2 rounded-full bg-emerald-500" />Strong match <b>{strong}</b></p><p><span className="mr-2 inline-block h-2 w-2 rounded-full bg-blue-500" />Moderate match <b>{moderate}</b></p><p><span className="mr-2 inline-block h-2 w-2 rounded-full bg-slate-300" />Catalog courses <b>{total}</b></p></div></div></section>; }
function LearningPath({ matches }: { matches: Match[] }) { const steps = [{ title: 'Build core skills', copy: `${matches.filter((match) => match.missingSkillIds.length).length} resources address missing skills.` }, { title: 'Develop role alignment', copy: `${matches.filter((match) => match.roleAlignedSkillIds.length).length} resources map to role skills.` }, { title: 'Explore certifications', copy: 'Open legitimate provider links from the catalog.' }, { title: 'Apply your learning', copy: 'Use your roadmap and opportunities to decide next steps.' }]; return <section className="border border-[#dce7f2] bg-white p-5"><h2 className="flex items-center gap-2 text-sm font-bold text-[#10295d]"><TrendingIcon />Recommended learning path</h2><div className="relative mt-4 space-y-4 before:absolute before:left-[10px] before:top-2 before:h-[calc(100%-10px)] before:w-px before:bg-[#cfe0f5]">{steps.map((step, index) => <div key={step.title} className="relative flex gap-3"><span className="z-10 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-[#1559c7] text-[10px] font-bold text-white">{index + 1}</span><div><h3 className="text-xs font-bold text-[#10295d]">{step.title}</h3><p className="mt-1 text-[10px] leading-4 text-slate-500">{step.copy}</p></div></div>)}</div></section>; }
function TrendingIcon() { return <BarChart3 className="h-4 w-4 text-[#1559c7]" />; }
