import { ResumeParseSchema } from '../ai/schemas';
import { calculateResumeScore } from './scoring';
import type { ResumeParsedData } from './types';
const skill = '11111111-1111-4111-8111-111111111111';
const valid: ResumeParsedData = { contact: { links: [] }, education: ['B.Tech'], skills: ['React'], projects: ['Built a dashboard'], experience: [], certifications: [], achievements: [], evidenced_skill_ids: [skill], role_required_skill_ids: [skill], not_evidenced_skill_ids: [], strengths: ['Project evidence'], improvement_areas: ['Add measurable outcomes'], suggestions: ['Add a metric if you have one'], overall_assessment: 'The resume shows useful project evidence but needs clearer outcomes.', biggest_opportunity: 'Make implementation impact easier to scan.', priority_issues: [{ title: 'Strengthen project outcomes', priority: 'high', section: 'Projects', problem: 'The project describes work without a verified result.', why_it_matters: 'Outcomes help the target role assess contribution.', recommended_change: 'Add a verified result if one exists.' }], section_analysis: [{ section: 'Projects', status: 'needs_work', what_works: ['Technical project is present.'], what_is_weak: ['Outcome is unclear.'], recommended_improvement: ['Add the method and verified result.'] }], bullet_improvements: [{ section: 'Projects', original: 'Built a dashboard', issue: 'The verb is broad.', why_it_is_weak: 'It does not show implementation detail.', suggested: 'Built a dashboard using [verified technology], resulting in [add a verified metric if available].', missing_information: ['Technology and outcome'] }], ats_keywords: { present: ['React'], weak_or_missing: ['Role-specific outcomes'], placement_suggestions: ['Place the strongest relevant skills near the top.'], formatting_concerns: [], ordering_suggestions: [] }, career_alignment_analysis: { aligned_areas: ['Project evidence'], underrepresented_areas: ['Measured outcomes'], missing_role_evidence: ['Verified impact'], priority_changes: ['Clarify project outcomes'] }, resume_strategy: { emphasize: ['Project implementation'], reduce: [], reorder: [], remove: [], add_if_true: ['Verified outcomes'] }, action_plan: { fix_now: ['Clarify project outcomes'], improve_next: ['Add role-relevant detail'], optional_polish: [] }, reanalysis_focus: 'Revisit outcomes after adding verified details.' };
function assert(value: boolean, message: string) { if (!value) throw new Error(message); }
console.log('--- RUNNING RESUME COPILOT TESTS ---');
assert(ResumeParseSchema.safeParse(valid).success, 'Valid structured resume output passes schema');
assert(!ResumeParseSchema.safeParse({ ...valid, evidenced_skill_ids: ['not-a-uuid'] }).success, 'Invalid AI output is rejected');
assert(calculateResumeScore(valid) >= 0 && calculateResumeScore(valid) <= 100, 'Score remains bounded');
assert(calculateResumeScore(valid) === calculateResumeScore(valid), 'Identical structured input produces identical score');
assert(valid.not_evidenced_skill_ids.length === 0, 'Not evidenced is distinct from possession');
console.log('PASS: schema validation, deterministic score, bounds, and evidence-aware semantics');
