'use client';

import React, { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Bookmark, CheckCircle2, Compass, Filter, Search, Sparkles } from 'lucide-react';
import { Sidebar } from '@/components/layout/sidebar';
import { TopNav } from '@/components/layout/top-nav';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select } from '@/components/ui/select';
import { EmptyState } from '@/components/ui/empty-state';
import { LoadingState } from '@/components/ui/loading-state';
import { getCareerRolesList, toggleTargetCareerRole } from '@/lib/career/queries';

type SkillRequirement = { id: string; skill_id: string; skills?: { name?: string; category?: string } };
type Role = { id: string; title: string; category: string; description: string; growth_outlook?: string; salary_range?: string; career_role_skills?: SkillRequirement[] };

export default function CareerExplorerPage() {
  const [loading, setLoading] = useState(true); const [roles, setRoles] = useState<Role[]>([]); const [categories, setCategories] = useState<string[]>([]); const [targetCareers, setTargetCareers] = useState<string[]>([]); const [studentSkillIds, setStudentSkillIds] = useState<string[]>([]); const [selectedRole, setSelectedRole] = useState<Role | null>(null); const [search, setSearch] = useState(''); const [category, setCategory] = useState('all'); const [error, setError] = useState(''); const [toggling, setToggling] = useState<string | null>(null);

  useEffect(() => { const timer = setTimeout(() => { void (async () => { setLoading(true); setError(''); try { const result = await getCareerRolesList(search, category); if (!result.success) throw new Error(result.error); const nextRoles = (result.roles || []) as Role[]; setRoles(nextRoles); setCategories(result.allCategories || []); setTargetCareers(result.studentTargetCareers || []); setStudentSkillIds(result.studentSkillIds || []); setSelectedRole((current) => current && nextRoles.some((role) => role.id === current.id) ? current : nextRoles[0] || null); } catch (err: unknown) { setError(err instanceof Error ? err.message : 'Career catalog is unavailable.'); } finally { setLoading(false); } })(); }, 250); return () => clearTimeout(timer); }, [search, category]);

  async function toggle(role: Role, event?: React.MouseEvent) { event?.preventDefault(); event?.stopPropagation(); setToggling(role.id); try { const result = await toggleTargetCareerRole(role.id); if (result.success && result.targetCareers) setTargetCareers(result.targetCareers); } finally { setToggling(null); } }
  const isTarget = (role: Role) => targetCareers.includes(role.id) || targetCareers.includes(role.title);

  return <div className="min-h-screen bg-[#f4f8fc] flex"><Sidebar /><div className="flex min-w-0 flex-1 flex-col"><TopNav /><main className="mx-auto w-full max-w-[1440px] flex-1 space-y-4 p-4 sm:p-6">
    <section className="relative min-h-[170px] overflow-hidden border border-blue-100 bg-[#e8f2ff] px-5 py-7 sm:px-8"><div className="absolute inset-y-0 right-0 w-1/2 bg-[url('/career-hero.jpg')] bg-cover bg-right opacity-40" /><div className="absolute inset-0 bg-gradient-to-r from-[#e8f2ff] via-[#e8f2ff]/90 to-transparent" /><div className="relative max-w-[500px]"><p className="text-xs font-bold uppercase tracking-[0.22em] text-[#1559c7]">Career recommendations</p><h1 className="mt-2 text-3xl font-extrabold text-[#10295d] sm:text-4xl">Careers that fit you</h1><p className="mt-2 text-sm leading-5 text-[#536987]">Explore catalog career roles using your skills, interests, and target-career selections.</p><div className="mt-4 flex items-center gap-2 bg-white/70 px-3 py-2 text-xs italic text-[#536987]"><span className="text-xl text-[#1559c7]">“</span>Your skills can build a stronger Madhya Pradesh tomorrow.</div></div></section>
    <section className="flex flex-col gap-3 border-b border-[#dce7f2] bg-white px-3 py-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-1 overflow-x-auto text-sm font-semibold"><button className="border-b-2 border-[#1559c7] px-3 py-2 text-[#1559c7]">AI Recommended</button><button className="px-3 py-2 text-slate-500">Explore All Careers</button><button className="px-3 py-2 text-slate-500">Selected Targets ({targetCareers.length})</button></div><div className="flex gap-2"><div className="relative min-w-0 flex-1 sm:w-64"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search careers or skills" className="h-9 pl-9 text-xs" /></div><Select value={category} onChange={(event) => setCategory(event.target.value)} className="h-9 w-40 text-xs"><option value="all">All categories</option>{categories.map((item) => <option key={item} value={item}>{item}</option>)}</Select><Filter className="mt-2 hidden h-4 w-4 text-slate-400 sm:block" /></div></section>
    {loading ? <div className="flex min-h-[360px] items-center justify-center"><LoadingState label="Searching career catalog..." /></div> : error ? <div className="border border-red-200 bg-red-50 p-6 text-sm text-red-700">{error}</div> : !roles.length ? <div className="bg-white p-10"><EmptyState icon={<Compass className="h-10 w-10 text-slate-400" />} title="No career roles found" description="Try another search or clear the category filter." actionLabel="Clear filters" onAction={() => { setSearch(''); setCategory('all'); }} /></div> : <div className="grid grid-cols-1 gap-4 xl:grid-cols-[1.05fr_0.95fr]"><section className="border border-[#dce7f2] bg-white"><div className="flex items-center justify-between border-b border-[#e5edf5] px-5 py-4"><div><h2 className="flex items-center gap-2 text-base font-bold text-[#10295d]"><Sparkles className="h-4.5 w-4.5 text-[#1559c7]" />Top career recommendations</h2><p className="mt-1 text-xs text-slate-500">Catalog roles ranked for exploration using your available profile context.</p></div><span className="text-xs text-[#1559c7]">{roles.length} roles</span></div><div className="divide-y divide-[#e5edf5]">{roles.map((role, index) => { const target = isTarget(role); return <div key={role.id} onClick={() => setSelectedRole(role)} className={`flex cursor-pointer gap-3 px-5 py-4 transition-colors ${selectedRole?.id === role.id ? 'bg-[#f0f6ff]' : 'hover:bg-[#f8fbff]'}`}><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-[#edf4ff] text-sm font-bold text-[#1559c7]">{index + 1}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg sm:text-xl font-bold text-[#10295d]">{role.title}</h3><Badge variant="secondary" className="text-xs">{role.category}</Badge>{target && <Badge variant="success" className="text-xs">Target role</Badge>}</div><p className="mt-1 line-clamp-2 text-xs text-slate-500">{role.description}</p><div className="mt-2 flex flex-wrap gap-1.5">{(role.career_role_skills || []).slice(0, 4).map((skill) => <span key={skill.id} className={`rounded-md border px-2 py-0.5 text-xs ${studentSkillIds.includes(skill.skill_id) ? 'border-emerald-200 bg-emerald-50 text-emerald-800' : 'border-slate-200 bg-slate-50 text-slate-600'}`}>{skill.skills?.name || 'Catalog skill'}</span>)}</div></div><div className="flex flex-col items-end gap-3"><button type="button" aria-label={target ? 'Remove target role' : 'Set target role'} onClick={(event) => void toggle(role, event)} className={`rounded-md border p-1.5 ${target ? 'border-emerald-300 bg-emerald-50 text-emerald-700' : 'border-slate-200 text-slate-400'}`} disabled={toggling === role.id}><Bookmark className={`h-4 w-4 ${target ? 'fill-current' : ''}`} /></button><Link href={`/career/${role.id}`} className="text-xs font-semibold text-[#1559c7]">Details <ArrowRight className="inline h-3.5 w-3.5" /></Link></div></div>; })}</div></section>
      {selectedRole && <aside className="border border-[#cfe0f5] bg-white"><div className="border-b border-[#e5edf5] px-5 py-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-[#1559c7]">Selected career role</p><h2 className="mt-1 text-2xl font-extrabold text-[#10295d]">{selectedRole.title}</h2><p className="mt-1 text-xs text-slate-500">{selectedRole.category}</p></div><Badge variant={isTarget(selectedRole) ? 'success' : 'info'} className="text-xs">{isTarget(selectedRole) ? 'Target role' : 'Explore'}</Badge></div></div><div className="p-5"><div className="mb-4 flex gap-1 border-b border-[#e5edf5] text-xs font-semibold"><span className="border-b-2 border-[#1559c7] px-2 pb-2 text-[#1559c7]">Overview</span><span className="px-2 pb-2 text-slate-400">Skills required</span><span className="px-2 pb-2 text-slate-400">Career fit</span></div><p className="text-base leading-6 text-[#536987]">{selectedRole.description}</p><div className="mt-5 grid grid-cols-2 gap-2"><div className="bg-[#f5f9fd] p-3"><p className="text-xs text-slate-500 font-medium">Growth outlook</p><p className="mt-1 text-sm font-bold text-[#10295d]">{selectedRole.growth_outlook || 'Not available'}</p></div><div className="bg-[#f5f9fd] p-3"><p className="text-xs text-slate-500 font-medium">Salary range</p><p className="mt-1 text-sm font-bold text-[#10295d]">{selectedRole.salary_range || 'Not available'}</p></div></div><h3 className="mt-6 text-sm font-bold text-[#10295d]">Skills required</h3><div className="mt-3 space-y-2">{(selectedRole.career_role_skills || []).slice(0, 8).map((skill) => <div key={skill.id} className="flex items-center justify-between gap-3 text-xs"><span className="text-slate-600">{skill.skills?.name || 'Catalog skill'}</span>{studentSkillIds.includes(skill.skill_id) ? <span className="flex items-center gap-1 text-emerald-700 font-medium"><CheckCircle2 className="h-3.5 w-3.5" />Acquired</span> : <span className="text-amber-700 font-medium">To develop</span>}</div>)}</div><div className="mt-6 flex gap-2"><Link href={`/career/${selectedRole.id}`} className="flex-1"><Button variant="govt" className="w-full text-xs" size="sm">View career detail <ArrowRight className="h-4 w-4" /></Button></Link><button type="button" aria-label="Save target career" onClick={() => void toggle(selectedRole)} className="rounded-md border border-[#9dbce7] px-3 text-[#1559c7]" disabled={toggling === selectedRole.id}><Bookmark className={`h-4 w-4 ${isTarget(selectedRole) ? 'fill-current' : ''}`} /></button></div></div></aside>}</div>}
  </main></div></div>;
}
