-- Restore the normalized catalog relationships required by readiness, skill gaps,
-- roadmap generation, course matching, and interview context. The inserts are
-- idempotent and resolve only existing catalog rows; they never create roles or
-- skills during a request.
WITH role_skills(role_title, skill_name, importance) AS (
  VALUES
    ('Software Developer', 'Python', 'high'),
    ('Software Developer', 'JavaScript', 'high'),
    ('Software Developer', 'HTML/CSS', 'medium'),
    ('Software Developer', 'Data Structures & Algorithms', 'high'),
    ('Software Developer', 'Git & Version Control', 'medium'),
    ('Software Developer', 'SQL', 'medium'),
    ('Software Developer', 'REST API Development', 'medium'),
    ('Data Analyst', 'SQL', 'high'),
    ('Data Analyst', 'Excel & Advanced Formulas', 'high'),
    ('Data Analyst', 'Python', 'medium'),
    ('Data Analyst', 'Pandas & NumPy', 'high'),
    ('Data Analyst', 'Statistics & Probability', 'high'),
    ('Data Analyst', 'PowerBI', 'medium'),
    ('Data Analyst', 'Tableau', 'medium'),
    ('Data Scientist', 'Python', 'high'),
    ('Data Scientist', 'SQL', 'medium'),
    ('Data Scientist', 'Pandas & NumPy', 'high'),
    ('Data Scientist', 'Statistics & Probability', 'high'),
    ('Data Scientist', 'Machine Learning Basics', 'high'),
    ('Data Scientist', 'Deep Learning & PyTorch', 'medium'),
    ('Data Scientist', 'Data Structures & Algorithms', 'medium'),
    ('Cybersecurity Analyst', 'Cybersecurity Fundamentals', 'high'),
    ('Cybersecurity Analyst', 'Network Security', 'high'),
    ('Cybersecurity Analyst', 'Penetration Testing', 'medium'),
    ('Cybersecurity Analyst', 'Security Audit & Compliance', 'medium'),
    ('Cybersecurity Analyst', 'Linux Administration', 'medium'),
    ('Cloud Engineer', 'AWS Cloud Fundamentals', 'high'),
    ('Cloud Engineer', 'Linux Administration', 'medium'),
    ('Cloud Engineer', 'Docker & Containers', 'high'),
    ('Cloud Engineer', 'Kubernetes', 'medium'),
    ('Cloud Engineer', 'System Design', 'high'),
    ('UI/UX Designer', 'Figma & UI Design', 'high'),
    ('UI/UX Designer', 'User Research & Wireframing', 'high'),
    ('UI/UX Designer', 'Communication Skills', 'medium'),
    ('Product Manager', 'Product Management', 'high'),
    ('Product Manager', 'Agile & Scrum Methodologies', 'high'),
    ('Product Manager', 'Communication Skills', 'high'),
    ('Product Manager', 'Business Analysis', 'medium'),
    ('Electronics Engineer', 'Embedded C/C++', 'high'),
    ('Electronics Engineer', 'PCB Design & VLSI', 'medium'),
    ('Electronics Engineer', 'Internet of Things (IoT)', 'medium'),
    ('Business Analyst', 'Business Analysis', 'high'),
    ('Business Analyst', 'Excel & Advanced Formulas', 'high'),
    ('Business Analyst', 'SQL', 'medium'),
    ('Business Analyst', 'Communication Skills', 'medium'),
    ('Digital Marketing Specialist', 'Digital Marketing & SEO', 'high'),
    ('Digital Marketing Specialist', 'Content Strategy', 'high'),
    ('Digital Marketing Specialist', 'Communication Skills', 'medium'),
    ('DevOps Engineer', 'Docker & Containers', 'high'),
    ('DevOps Engineer', 'Kubernetes', 'high'),
    ('DevOps Engineer', 'CI/CD Pipelines', 'high'),
    ('DevOps Engineer', 'Linux Administration', 'medium'),
    ('DevOps Engineer', 'AWS Cloud Fundamentals', 'medium'),
    ('Full Stack Developer', 'HTML/CSS', 'high'),
    ('Full Stack Developer', 'JavaScript', 'high'),
    ('Full Stack Developer', 'React', 'high'),
    ('Full Stack Developer', 'Node.js', 'high'),
    ('Full Stack Developer', 'REST API Development', 'medium'),
    ('Full Stack Developer', 'SQL', 'medium'),
    ('Full Stack Developer', 'Git & Version Control', 'medium'),
    ('Systems Engineer', 'Linux Administration', 'high'),
    ('Systems Engineer', 'Network Security', 'medium'),
    ('Systems Engineer', 'System Design', 'high'),
    ('Systems Engineer', 'Docker & Containers', 'medium'),
    ('Embedded Systems Engineer', 'Embedded C/C++', 'high'),
    ('Embedded Systems Engineer', 'PCB Design & VLSI', 'medium'),
    ('Embedded Systems Engineer', 'Internet of Things (IoT)', 'high'),
    ('Network Engineer', 'Network Security', 'high'),
    ('Network Engineer', 'Linux Administration', 'medium'),
    ('Network Engineer', 'System Design', 'medium'),
    ('QA Automation Engineer', 'JavaScript', 'high'),
    ('QA Automation Engineer', 'Python', 'medium'),
    ('QA Automation Engineer', 'Git & Version Control', 'medium'),
    ('QA Automation Engineer', 'REST API Development', 'medium'),
    ('QA Automation Engineer', 'Communication Skills', 'low'),
    ('Database Administrator', 'PostgreSQL Database', 'high'),
    ('Database Administrator', 'Database Administration', 'high'),
    ('Database Administrator', 'SQL', 'high')
)
INSERT INTO public.career_role_skills (role_id, skill_id, required, importance)
SELECT roles.id, skills.id, true, role_skills.importance
FROM role_skills
JOIN public.career_roles AS roles ON roles.title = role_skills.role_title
JOIN public.skills AS skills ON skills.name = role_skills.skill_name
ON CONFLICT (role_id, skill_id) DO UPDATE
SET required = EXCLUDED.required, importance = EXCLUDED.importance;
